name: Test

on:
  push:
    branches:
      - main

jobs:
  t1:
    name: t1
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        options: >-
          --health-cmd "mysqladmin ping -h localhost"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 3306:3306
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'main'

      - name: Set up Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Migrate DB
        run: go run cmd/mig_for_ga/main.go

      - name: all go test
        run: ./all_test.sh
